#!/bin/sh

case "$1" in
    remove)
        systemctl stop aceproxy > /dev/null 2>&1 || true
        systemctl disable aceproxy > /dev/null 2>&1 || true
        stop aceproxy > /dev/null 2>&1 || true
    ;;
esac

