#!/bin/sh
set -e


case "$1" in
    install)
        . /usr/share/debconf/confmodule
        db_subst wicard-installer/confirm WICARD_URL '@WICARD_URL@' || true
        db_input high wicard-installer/confirm || true
        db_go || true
        db_get wicard-installer/confirm
        
        if ! $RET
        then
            db_purge
            exit 1
        fi
    ;;

    upgrade|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
