#!/bin/sh
set -e


case "$1" in
    configure)
        URL='@URL@'
        VERSION='@VERSION@'
        TMP_DIR="$(mktemp -d)"
        ZIP_FILE="$TMP_DIR/gradle-$VERSION-bin.zip"
        trap "rm -rf $TMP_DIR" EXIT HUP INT QUIT TERM
        
        echo "Downloading $URL"
        wget -O "$ZIP_FILE" "$URL"
        
        echo "Installing..."
        unzip "$ZIP_FILE" -d "$TMP_DIR" > /dev/null
        rm -rf "/usr/lib/gradle/$VERSION"
        mkdir -p /usr/lib/gradle
        mv "$TMP_DIR/gradle-$VERSION" "/usr/lib/gradle/$VERSION"
        rm -rf "$TMP_DIR"
        rm -rf /usr/lib/gradle/default
        ln -s "/usr/lib/gradle/$VERSION" /usr/lib/gradle/default
        chmod a+x /usr/lib/gradle/default/bin/gradle
        update-alternatives --install /usr/bin/gradle gradle /usr/lib/gradle/default/bin/gradle 100
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
