#!/bin/sh

case "$1" in
    purge|remove)
        update-alternatives --remove gradle /usr/lib/gradle/default/bin/gradle || true
        rm -rf '/usr/lib/gradle/@VERSION@' '/usr/lib/gradle/default'
        rmdir --ignore-fail-on-non-empty '/usr/lib/gradle' 2>/dev/null || true
    ;;
esac
